/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ua_khpi_oop_lab16_NativeThresholdFilter */

#ifndef _Included_ua_khpi_oop_lab16_NativeThresholdFilter
#define _Included_ua_khpi_oop_lab16_NativeThresholdFilter
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ua_khpi_oop_lab16_NativeThresholdFilter
 * Method:    filter
 * Signature: ([II)[I
 */
JNIEXPORT jintArray JNICALL Java_ua_khpi_oop_lab16_NativeThresholdFilter_filter
  (JNIEnv *, jobject, jintArray, jint);

#ifdef __cplusplus
}
#endif
#endif
